# Generated by Django 5.1.7 on 2025-04-28 16:11

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church', models.CharField(choices=[('Achimota', 'Achimota'), ('Prince of Peace', 'Prince of Peace'), ('King of Glory', 'King of Glory'), ('Nii Boi Town', 'Nii Boi Town'), ('Israel', 'Israel')], default='Achimota', max_length=20)),
                ('department', models.CharField(choices=[('Treasury', 'Treasury'), ('Secretariat', 'Secretariat'), ('Deaconry', 'Deaconry'), ('Sabbath School', 'Sabbath School'), ('Religious Liberty/VOP', 'Religious Liberty/VOP'), ('Health', 'Health'), ('Stewardship', 'Stewardship'), ('Personal Ministry', 'Personal Ministry'), ('Possibility Ministry', 'Possibility Ministry'), ('Communication', 'Communication'), ('Children Ministry', 'Children Ministry'), ('Publishing Ministry', 'Publishing Ministry'), ('Music', 'Music'), ('Adventist Men Ministry', 'Adventist Men Ministry'), ('Womens Ministry', 'Womens Ministry'), ('Audit', 'Audit'), ('Adventurer', 'Adventurer'), ('Young Adult', 'Young Adult'), ('Public Campus Ministry', 'Public Campus Ministry'), ('Ambassador', 'Ambassador'), ('Pathfinder', 'Pathfinder'), ('Family Ministry', 'Family Ministry'), ('Education', 'Education'), ('Welfare', 'Welfare'), ('PA System', 'PA System'), ('Interest Coordinator', 'Interest Coordinator'), ('Community Service', 'Community Service'), ('Project', 'Project'), ('Congregation', 'Congregation')], default='', max_length=50)),
                ('program', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('typ', models.CharField(choices=[('local', 'local'), ('district', 'district'), ('zonal', 'zonal'), ('conference', 'conference')], default='conference', max_length=10)),
                ('facilitator', models.CharField(blank=True, max_length=255, null=True)),
                ('expense', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rating', models.CharField(blank=True, choices=[('Poor', 'Poor'), ('Fair', 'Fair'), ('Good', 'Good'), ('Very Good', 'Very Good'), ('Excellent', 'Excellent')], default='Good', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church', models.CharField(choices=[('Achimota', 'Achimota'), ('Prince of Peace', 'Prince of Peace'), ('King of Glory', 'King of Glory'), ('Nii Boi Town', 'Nii Boi Town'), ('Israel', 'Israel')], default='', max_length=25)),
                ('date', models.DateField()),
                ('service', models.CharField(choices=[('Mid-Week Service', 'Mid-Week Service'), ('Bible Studies', 'Bible Studies'), ('Sabbath School', 'Sabbath School'), ('Divine Service', 'Divine Service'), ('Others', 'Others')], max_length=20)),
                ('adult', models.PositiveIntegerField()),
                ('youth', models.PositiveIntegerField()),
                ('children', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Baptism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('local', 'local'), ('district', 'district'), ('zonal', 'zonal'), ('conference', 'conference')], default='local', max_length=10)),
                ('date_of_birth', models.DateField()),
                ('first_name', models.CharField(max_length=255)),
                ('other_names', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_church_voted', models.DateField()),
                ('date_baptized', models.DateField()),
                ('church', models.CharField(choices=[('Achimota', 'Achimota'), ('Prince of Peace', 'Prince of Peace'), ('King of Glory', 'King of Glory'), ('Nii Boi Town', 'Nii Boi Town'), ('Israel', 'Israel')], max_length=25)),
                ('minutes_number', models.CharField(max_length=100)),
                ('baptized_by', models.CharField(max_length=255)),
                ('place_baptized', models.CharField(max_length=255)),
                ('mothers_name', models.CharField(blank=True, max_length=255, null=True)),
                ('fathers_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church', models.CharField(choices=[('Achimota', 'Achimota'), ('Prince of Peace', 'Prince of Peace'), ('King of Glory', 'King of Glory'), ('Nii Boi Town', 'Nii Boi Town'), ('Israel', 'Israel')], max_length=25)),
                ('date', models.DateField()),
                ('child_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church', models.CharField(choices=[('Achimota', 'Achimota'), ('Prince of Peace', 'Prince of Peace'), ('King of Glory', 'King of Glory'), ('Nii Boi Town', 'Nii Boi Town'), ('Israel', 'Israel')], default='Achimota', max_length=25)),
                ('date', models.DateField()),
                ('event_type', models.CharField(choices=[('Marriage', 'Marriage'), ('Funeral', 'Funeral'), ('Communion', 'Communion'), ('Community service', 'Community service'), ('Outreach/Visitation', 'Outreach/Visitation'), ('Child birth', 'Child birth'), ('Other', 'Other')], max_length=50)),
                ('event_place', models.CharField(max_length=255)),
                ('member_involved', models.CharField(max_length=255)),
                ('event_detail', models.TextField()),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pastor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church', models.CharField(choices=[('Achimota', 'Achimota'), ('Prince of Peace', 'Prince of Peace'), ('King of Glory', 'King of Glory'), ('Nii Boi Town', 'Nii Boi Town'), ('Israel', 'Israel')], default='Achimota', max_length=25)),
                ('typ', models.CharField(choices=[('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out')], default='transfer_in', max_length=15)),
                ('first_name', models.CharField(max_length=255)),
                ('other_names', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_church_voted', models.DateField()),
                ('minutes_number', models.CharField(max_length=100)),
                ('sending_church', models.CharField(blank=True, max_length=255, null=True)),
                ('receiving_church', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('contact', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church', models.CharField(choices=[('Achimota', 'Achimota'), ('Prince of Peace', 'Prince of Peace'), ('King of Glory', 'King of Glory'), ('Nii Boi Town', 'Nii Boi Town'), ('Israel', 'Israel')], default='Achimota', max_length=25)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('place', models.CharField(default='', max_length=255)),
                ('status', models.CharField(choices=[('adventist', 'Adventist'), ('non_adventist', 'Non-Adventist')], max_length=15)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('church', models.CharField(choices=[('Achimota', 'Achimota'), ('Prince of Peace', 'Prince of Peace'), ('King of Glory', 'King of Glory'), ('Nii Boi Town', 'Nii Boi Town'), ('Israel', 'Israel')], max_length=25)),
                ('department', models.CharField(choices=[('Treasury', 'Treasury'), ('Secretariat', 'Secretariat'), ('Deaconry', 'Deaconry'), ('Sabbath School', 'Sabbath School'), ('Religious Liberty/VOP', 'Religious Liberty/VOP'), ('Health', 'Health'), ('Stewardship', 'Stewardship'), ('Personal Ministry', 'Personal Ministry'), ('Possibility Ministry', 'Possibility Ministry'), ('Communication', 'Communication'), ('Children Ministry', 'Children Ministry'), ('Publishing Ministry', 'Publishing Ministry'), ('Music', 'Music'), ('Adventist Men Ministry', 'Adventist Men Ministry'), ('Womens Ministry', 'Womens Ministry'), ('Audit', 'Audit'), ('Adventurer', 'Adventurer'), ('Young Adult', 'Young Adult'), ('Public Campus Ministry', 'Public Campus Ministry'), ('Ambassador', 'Ambassador'), ('Pathfinder', 'Pathfinder'), ('Family Ministry', 'Family Ministry'), ('Education', 'Education'), ('Welfare', 'Welfare'), ('PA System', 'PA System'), ('Interest Coordinator', 'Interest Coordinator'), ('Community Service', 'Community Service'), ('Project', 'Project'), ('Congregation', 'Congregation')], max_length=50)),
                ('contact', models.CharField(blank=True, max_length=10)),
                ('is_local', models.BooleanField(default=False)),
                ('is_district', models.BooleanField(default=False)),
                ('is_officer', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
