# Generated by Django 5.1.7 on 2025-05-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baptism',
            name='minutes_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='baptism',
            name='place_baptized',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
