# Generated by Django 5.1.7 on 2025-04-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='department',
            field=models.CharField(choices=[('Treasury', 'Treasury'), ('Secretariat', 'Secretariat'), ('Deaconry', 'Deaconry'), ('Sabbath School', 'Sabbath School'), ('Religious Liberty/VOP', 'Religious Liberty/VOP'), ('Health', 'Health'), ('Stewardship', 'Stewardship'), ('Personal Ministry', 'Personal Ministry'), ('Possibility Ministry', 'Possibility Ministry'), ('Communication', 'Communication'), ('Children Ministry', 'Children Ministry'), ('Publishing Ministry', 'Publishing Ministry'), ('Music', 'Music'), ('Adventist Men Ministry', 'Adventist Men Ministry'), ('Womens Ministry', 'Womens Ministry'), ('Audit', 'Audit'), ('Youth', 'Youth'), ('Family Ministry', 'Family Ministry'), ('Education', 'Education'), ('Welfare', 'Welfare'), ('PA System', 'PA System'), ('Interest Coordinator', 'Interest Coordinator'), ('Community Service', 'Community Service'), ('Project', 'Project'), ('Congregation', 'Congregation')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='department',
            field=models.CharField(choices=[('Treasury', 'Treasury'), ('Secretariat', 'Secretariat'), ('Deaconry', 'Deaconry'), ('Sabbath School', 'Sabbath School'), ('Religious Liberty/VOP', 'Religious Liberty/VOP'), ('Health', 'Health'), ('Stewardship', 'Stewardship'), ('Personal Ministry', 'Personal Ministry'), ('Possibility Ministry', 'Possibility Ministry'), ('Communication', 'Communication'), ('Children Ministry', 'Children Ministry'), ('Publishing Ministry', 'Publishing Ministry'), ('Music', 'Music'), ('Adventist Men Ministry', 'Adventist Men Ministry'), ('Womens Ministry', 'Womens Ministry'), ('Audit', 'Audit'), ('Youth', 'Youth'), ('Family Ministry', 'Family Ministry'), ('Education', 'Education'), ('Welfare', 'Welfare'), ('PA System', 'PA System'), ('Interest Coordinator', 'Interest Coordinator'), ('Community Service', 'Community Service'), ('Project', 'Project'), ('Congregation', 'Congregation')], max_length=50),
        ),
    ]
