# Generated by Django 5.1.7 on 2025-05-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_baptism_minutes_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='date_church_voted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='minutes_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
