# Generated by Django 5.1.7 on 2025-04-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_activity_department_alter_appuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='contact',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
