# Generated by Django 5.2.1 on 2025-05-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_alter_transfer_date_church_voted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treasury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church', models.CharField(choices=[('Achimota', 'Achimota'), ('Prince of Peace', 'Prince of Peace'), ('King of Glory', 'King of Glory'), ('Nii Boi Town', 'Nii Boi Town'), ('Israel', 'Israel')], max_length=25)),
                ('date', models.DateField()),
                ('department', models.CharField(choices=[('Treasury', 'Treasury'), ('Secretariat', 'Secretariat'), ('Deaconry', 'Deaconry'), ('Sabbath School', 'Sabbath School'), ('Religious Liberty/VOP', 'Religious Liberty/VOP'), ('Health', 'Health'), ('Stewardship', 'Stewardship'), ('Personal Ministry', 'Personal Ministry'), ('Possibility Ministry', 'Possibility Ministry'), ('Communication', 'Communication'), ('Children Ministry', 'Children Ministry'), ('Publishing Ministry', 'Publishing Ministry'), ('Music', 'Music'), ('Adventist Men Ministry', 'Adventist Men Ministry'), ('Womens Ministry', 'Womens Ministry'), ('Audit', 'Audit'), ('Youth', 'Youth'), ('Family Ministry', 'Family Ministry'), ('Education', 'Education'), ('Welfare', 'Welfare'), ('PA System', 'PA System'), ('Interest Coordinator', 'Interest Coordinator'), ('Community Service', 'Community Service'), ('Project', 'Project'), ('Congregation', 'Congregation'), ('admin', 'admin')], default='', max_length=50)),
                ('returnees', models.PositiveIntegerField()),
                ('tithe', models.FloatField()),
                ('combined', models.FloatField()),
                ('loose', models.FloatField()),
                ('other_receipts', models.FloatField()),
                ('payments', models.FloatField()),
            ],
        ),
    ]
